gantt
    title Corporate Credit Card Launch
    dateFormat  YYYY-MM-DD
    
    section Pre-launch
        Market Research   :done,    des1, 2023-01-01, 2023-01-03
        Card Design                    :active,        des4, 2023-01-02, 3d
    section Development
        Integration          :        des5, 2023-01-04, 2023-01-06
        Testing                        :crit,  milestone, des8, 2023-01-06, 2023-01-09
    section Marketing & Launch
        Ad Creation, Launch & Issuing  :        des10, after des5, 3d
    section Post-launch
        Analyze Feedback & Improvements:        des15, 2023-01-06, 2023-01-10
