mindmap
    Marketing Campaign
        Objectives
        ::icon(fa fa-bullseye)
        Strategies
        ::icon(fa fa-cogs)
        Target Audience
        ::icon(fa fa-users)
        Channels
        ::icon(fa fa-broadcast-tower)
            Social Media
            ::icon(fa fa-share-alt)
            Email
            ::icon(fa fa-envelope)
            Print Media
            ::icon(fa fa-newspaper)
            Web Advertising
            ::icon(fa fa-globe-americas)
        Metrics & KPIs
        ::icon(fa fa-chart-line)
        Budget
        ::icon(fa fa-dollar-sign)
        Content Ideas
        ::icon(fa fa-lightbulb)
        Execution Timeline
        ::icon(fa fa-calendar-check)
